/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatrmi.view;

import com.mycompany.chatrmi.model.ChatConfig;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/**
 *
 * @author Carlos Dominguez Figueiras <carlosdominguezfigueiras@gmail.com>
 */
public class ChatJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChatJFrame
     */
    public ChatJFrame(ChatConfig config) {
        initComponents();
        setDefaultValues(config);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        localPortLabel = new javax.swing.JLabel();
        localPortTextField = new javax.swing.JTextField();
        localNameLabel = new javax.swing.JLabel();
        localNameTextField = new javax.swing.JTextField();
        remoteHostLabel = new javax.swing.JLabel();
        remoteHostTextField = new javax.swing.JTextField();
        remotePortLabel = new javax.swing.JLabel();
        remotePortTextField = new javax.swing.JTextField();
        remoteNameLabel = new javax.swing.JLabel();
        remoteNameTextField = new javax.swing.JTextField();
        publishButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();
        chatScrollPane = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        messageTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat RMI P2P");

        configPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion del nodo"));

        userLabel.setText("Usuario:");

        localPortLabel.setText("Puerto local:");

        localNameLabel.setText("Nombre local:");

        remoteHostLabel.setText("Host remoto:");

        remotePortLabel.setText("Puerto remoto:");

        remoteNameLabel.setText("Nombre remoto:");

        publishButton.setText("Publicar");

        connectButton.setText("Conectar");

        GroupLayout configPanelLayout = new GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
                configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(configPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(userLabel)
                                        .addComponent(localNameLabel)
                                        .addComponent(remotePortLabel))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(userTextField, GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(localNameTextField)
                                        .addComponent(remotePortTextField))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(localPortLabel)
                                        .addComponent(remoteHostLabel)
                                        .addComponent(remoteNameLabel))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(localPortTextField, GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                        .addComponent(remoteHostTextField)
                                        .addComponent(remoteNameTextField))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(publishButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(connectButton, GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addContainerGap())
        );
        configPanelLayout.setVerticalGroup(
                configPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(configPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(userLabel)
                                        .addComponent(userTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(localPortLabel)
                                        .addComponent(localPortTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(publishButton))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(localNameLabel)
                                        .addComponent(localNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(remoteHostLabel)
                                        .addComponent(remoteHostTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(connectButton))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(remotePortLabel)
                                        .addComponent(remotePortTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(remoteNameLabel)
                                        .addComponent(remoteNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chatTextArea.setColumns(20);
        chatTextArea.setEditable(false);
        chatTextArea.setLineWrap(true);
        chatTextArea.setRows(5);
        chatTextArea.setWrapStyleWord(true);
        chatScrollPane.setViewportView(chatTextArea);

        sendButton.setText("Enviar");

        fileMenu.setText("Archivo");

        exitMenu.setText("Salir");
        fileMenu.add(exitMenu);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(configPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chatScrollPane)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(messageTextField)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sendButton, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(configPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chatScrollPane, GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(messageTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sendButton))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public ChatConfig getChatConfig() {
        return new ChatConfig(userTextField.getText(), Integer.parseInt(localPortTextField.getText()),
                localNameTextField.getText(), remoteHostTextField.getText(),
                Integer.parseInt(remotePortTextField.getText()), remoteNameTextField.getText());
    }

    public String getMessage() {
        return messageTextField.getText();
    }

    public void clearMessage() {
        messageTextField.setText("");
    }

    public void addOwnMessage(String from, String message) {
        appendMessage(from + " -> " + message);
    }

    public void addRemoteMessage(String from, String message) {
        appendMessage(from + " <- " + message);
    }

    public void addSystemMessage(String message) {
        appendMessage("[Sistema] " + message);
    }

    public void setPublished(boolean published) {
        publishButton.setText(published ? "Publicado" : "Publicar");
    }

    public void setConnected(boolean connected) {
        connectButton.setText(connected ? "Conectado" : "Conectar");
    }

    public void publishButtonAddActionListener(ActionListener al) {
        this.publishButton.addActionListener(al);
    }

    public void connectButtonAddActionListener(ActionListener al) {
        this.connectButton.addActionListener(al);
    }

    public void sendButtonAddActionListener(ActionListener al) {
        this.sendButton.addActionListener(al);
        this.messageTextField.addActionListener(al);
    }

    public void exitMenuAddActionListener(ActionListener al) {
        this.exitMenu.addActionListener(al);
    }

    private void setDefaultValues(ChatConfig config) {
        userTextField.setText(config.getUserName());
        localPortTextField.setText(String.valueOf(config.getLocalPort()));
        localNameTextField.setText(config.getLocalServiceName());
        remoteHostTextField.setText(config.getRemoteHost());
        remotePortTextField.setText(String.valueOf(config.getRemotePort()));
        remoteNameTextField.setText(config.getRemoteServiceName());
    }

    private void appendMessage(String text) {
        chatTextArea.append(text + System.lineSeparator());
        chatTextArea.setCaretPosition(chatTextArea.getDocument().getLength());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JScrollPane chatScrollPane;
    private javax.swing.JButton connectButton;
    private javax.swing.JPanel configPanel;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel localNameLabel;
    private javax.swing.JTextField localNameTextField;
    private javax.swing.JLabel localPortLabel;
    private javax.swing.JTextField localPortTextField;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JButton publishButton;
    private javax.swing.JLabel remoteHostLabel;
    private javax.swing.JTextField remoteHostTextField;
    private javax.swing.JLabel remoteNameLabel;
    private javax.swing.JTextField remoteNameTextField;
    private javax.swing.JLabel remotePortLabel;
    private javax.swing.JTextField remotePortTextField;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
